name: test_advance
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.0


dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8

  # State managment
  flutter_bloc: ^8.1.6
  
  # Code generator ( mainly used with cubit and retrofit ) Code generator ( mainly used with cubit and retrofit ) 
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4

  # For dependency injection
  get_it: ^7.7.0
  
  # Automaticly generating code for converting to and from json by annotation
  json_serializable: ^6.8.0
  
  # Annotaion for the json_serializable code_generator
  json_annotation: ^4.9.0
  
  # For api calling and networking 
  dio: ^5.6.0
  retrofit: ^4.2.0
  retrofit_generator: ^8.2.0
  pretty_dio_logger: ^1.4.0

  #
  shared_preferences: ^2.3.2
  intl: ^0.19.0
  easy_localization: ^3.0.7
  
  # For waiting starting screen
  flutter_native_splash: ^2.4.1


dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true